### ISSUE TITLE
Crash when i add Susy core addon

### ISSUE THREAD

**Issue by Castanea43** [SymmetricDevs/Susy-Core#192]
Hi, i'll try to make a new modpack, but when i add SusyCore (latest - 0.1.12) with GTCEU 2.8.6-beta
i also add Geckolib3 3.0.30

but still crash on 2/7 with Susy

crash log : https://mclo.gs/PJNJCBZ

Problem with the mods or need another dependencies ?
Thanks in advance.

**Comment by trainvoi** [comment]
you need universal mod core + immersive railroading

**Comment by Castanea43** [comment]
Thanks trainvoi, so i test on my modpack with a lot od mods, but still, crash i test to place a sapling on soil, it crashes

you can see the log here : https://mclo.gs/Anhkk2T (you have all mods at the end of the report)
But on server side it still running but log here : https://mclo.gs/lvXYPeu

There is a conflict with GTExpert ?
Thanks in advance.

**Comment by loxoDev** [comment]
On a side note, it really is not recommended to use this outside of SuSy, the mod is completely aligned with SuSy and as such contains quite a bit of redundancy for the normal player.
