### ISSUE TITLE
No Susy ores Secondary byproducts.

### ISSUE THREAD

**Issue by jude123412** [SymmetricDevs/Susy-Core#225]
Susy ores don't have any secondary ore product as an output.

This can be fixed by adding these lines of code to the SusyStoneTypes.java File.

<img width="643" alt="image" src="https://github.com/SymmetricDevs/Susy-Core/assets/104434396/63580c87-5e1e-42d2-872f-20962b18bf7e">

**Comment by trainvoi** [comment]
I don't think SUSY intends to have secondary ore product at all. If you look at the centrifuging/macerating recipe of most ores they gives pegmatite/limestone/granite tailings.

**Comment by loxoDev** [comment]
You can't actually get the ore variants, all drop the normal stone ones.

**Comment by jude123412** [comment]
Hmmm, Enabling the config in gregtech to enable all stone types to drop highlights this issue xD. I usally play with this enabled for more a elaborate gameplay.

**Comment by jude123412** [comment]
I suppose my suggestion is to implement this for players who want that config enabled so it fully supports that config option?

**Comment by loxoDev** [comment]
Alright sure

**Comment by loxoDev** [comment]
Eventually :tm:
